import type { Patient } from './types'

const basePatients: Patient[] = [
  {
    id: '1',
    number: 1,
    name: 'Ніна Нінченко Артем',
    avatar: '/avatars/patient1.jpg',
    status: 'being_treated',
    phoneNumber: '+3801111111',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment:
      'Початок тексту коментаря. Цей коментар містить детальний аналіз теми, яка обговорюється. Я хотів би підкреслити важливість кожного аспекту, що стосується даного питання.',
    registrationDate: '21.03.2024',
    nextVisit: '25.03.2024',
    nextReminder: '24.03.2024',
  },
  {
    id: '2',
    number: 2,
    name: 'Петро Васильович',
    avatar: '/avatars/patient2.jpg',
    status: 'did_not_visit',
    phoneNumber: '+3802222222',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Додатковий коментар',
    registrationDate: '22.03.2024',
    nextVisit: '26.03.2024',
    nextReminder: '25.03.2024',
  },
  {
    id: '3',
    number: 3,
    name: 'Олена Сергіївна',
    avatar: '/avatars/patient3.jpg',
    status: 'had_visit_no_treatment',
    phoneNumber: '+3803333333',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Технічні питання',
    registrationDate: '23.03.2024',
    nextVisit: '27.03.2024',
    nextReminder: '26.03.2024',
  },
  {
    id: '4',
    number: 4,
    name: 'Іван Петрович',
    avatar: '/avatars/patient4.jpg',
    status: 'checkup',
    phoneNumber: '+3804444444',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Запит на інформацію',
    registrationDate: '24.03.2024',
    nextVisit: '28.03.2024',
    nextReminder: '27.03.2024',
  },
  {
    id: '5',
    number: 5,
    name: 'Софія Андріївна',
    avatar: '/avatars/patient5.jpg',
    status: 'partially_treated',
    phoneNumber: '+3805555555',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Обговорення проекту',
    registrationDate: '25.03.2024',
    nextVisit: '29.03.2024',
    nextReminder: '28.03.2024',
  },
  {
    id: '6',
    number: 6,
    name: 'Олег Іванович',
    avatar: '/avatars/patient6.jpg',
    status: 'refused',
    phoneNumber: '+3806666666',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Статус проекту',
    registrationDate: '26.03.2024',
    nextVisit: '30.03.2024',
    nextReminder: '29.03.2024',
  },
  {
    id: '7',
    number: 7,
    name: 'Анна Володимирівна',
    avatar: '/avatars/patient7.jpg',
    status: 'being_treated',
    phoneNumber: '+3807777777',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Запит на зустріч',
    registrationDate: '27.03.2024',
    nextVisit: '31.03.2024',
    nextReminder: '30.03.2024',
  },
  {
    id: '8',
    number: 8,
    name: 'Дмитро Миколайович',
    avatar: '/avatars/patient8.jpg',
    status: 'did_not_visit',
    phoneNumber: '+3808888888',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Фінансові питання',
    registrationDate: '28.03.2024',
    nextVisit: '01.04.2024',
    nextReminder: '31.03.2024',
  },
  {
    id: '9',
    number: 9,
    name: 'Катерина Василівна',
    avatar: '/avatars/patient9.jpg',
    status: 'checkup',
    phoneNumber: '+3809999999',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Розгляд нових ідей',
    registrationDate: '29.03.2024',
    nextVisit: '02.04.2024',
    nextReminder: '01.04.2024',
  },
]

const additionalNames = [
  'Наталія Олександрівна',
  'Віктор Сергійович',
  'Людмила Іванівна',
  'Андрій Петрович',
  'Тетяна Миколаївна',
  'Сергій Володимирович',
  'Ірина Василівна',
  'Михайло Олегович',
  'Юлія Дмитрівна',
  'Олександр Андрійович',
  'Галина Сергіївна',
  'Володимир Іванович',
  'Світлана Петрівна',
  'Роман Миколайович',
  'Лариса Володимирівна',
  'Василь Олександрович',
  'Ніна Сергіївна',
  'Борис Іванович',
  'Зінаїда Петрівна',
  'Геннадій Миколайович',
  'Валентина Володимирівна',
  'Ігор Олександрович',
  'Раїса Сергіївна',
  'Леонід Іванович',
  'Маргарита Петрівна',
  'Віталій Миколайович',
  'Алла Володимирівна',
  'Станіслав Олександрович',
  'Римма Сергіївна',
  'Валерій Іванович',
  'Лідія Петрівна',
  'Артем Миколайович',
  'Оксана Володимирівна',
  'Руслан Олександрович',
  'Таміла Сергіївна',
  'Тарас Іванович',
  'Віра Петрівна',
  'Максим Миколайович',
  'Лариса Володимирівна',
  'Денис Олександрович',
  'Інна Сергіївна',
  'Віктор Іванович',
  'Ніна Петрівна',
  'Арсен Миколайович',
  'Олена Володимирівна',
  'Ростислав Олександрович',
  'Ганна Сергіївна',
]

const additionalPatients: Patient[] = additionalNames.map((name, index) => {
  const baseDate = new Date(2024, 2, 21) // March 21, 2024
  const registrationDate = new Date(baseDate)
  registrationDate.setDate(baseDate.getDate() + index)

  const nextVisit = new Date(registrationDate)
  nextVisit.setDate(registrationDate.getDate() + 4)

  const nextReminder = new Date(registrationDate)
  nextReminder.setDate(registrationDate.getDate() + 3)

  const statuses: Patient['status'][] = [
    'did_not_visit',
    'had_visit_no_treatment',
    'being_treated',
    'checkup',
    'partially_treated',
    'refused',
  ]
  const randomStatus = statuses[Math.floor(Math.random() * statuses.length)]

  return {
    id: (index + 10).toString(),
    number: index + 10,
    name,
    avatar: `/avatars/patient${index + 10}.jpg`,
    status: randomStatus,
    phoneNumber: `+380${(index + 10).toString().padStart(7, '0')}`,
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: `Коментар для ${name}`,
    registrationDate: registrationDate.toLocaleDateString('uk-UA'),
    nextVisit: nextVisit.toLocaleDateString('uk-UA'),
    nextReminder: nextReminder.toLocaleDateString('uk-UA'),
  }
})

export const mockPatients: Patient[] = [...basePatients, ...additionalPatients]

export const STATUS_LABELS = {
  did_not_visit: 'Не відвідував клініку',
  had_visit_no_treatment: 'Був візит і не почали лікування',
  being_treated: 'Лікується',
  checkup: 'Профогляд',
  partially_treated: 'Частково проліковано',
  refused: 'Відмова',
} as const

export const STATUS_COLORS = {
  did_not_visit: '#8e24aa',
  had_visit_no_treatment: '#ffb300',
  being_treated: '#43a047',
  checkup: '#003bcb',
  partially_treated: '#7cb342',
  refused: '#e53935',
} as const
