import type { Patient } from './types'

const basePatients: Patient[] = [
  {
    id: '1',
    number: 1,
    name: 'Ніна Нінченко Артем',
    avatar: '/avatars/patient1.jpg',
    status: 'being_treated',
    phoneNumber: '+3801111111',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment:
      'Початок тексту коментаря. Цей коментар містить детальний аналіз теми, яка обговорюється. Я хотів би підкреслити важливість кожного аспекту, що стосується даного питання.',
    registrationDate: '21.03.2024',
    nextVisit: '25.03.2024',
    nextReminder: '24.03.2024',
  },
  {
    id: '2',
    number: 2,
    name: 'Петро Васильович',
    avatar: '/avatars/patient2.jpg',
    status: 'did_not_visit',
    phoneNumber: '+3802222222',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Додатковий коментар',
    registrationDate: '22.03.2024',
    nextVisit: '26.03.2024',
    nextReminder: '25.03.2024',
  },
  {
    id: '3',
    number: 3,
    name: 'Олена Сергіївна',
    avatar: '/avatars/patient3.jpg',
    status: 'had_visit_no_treatment',
    phoneNumber: '+3803333333',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Технічні питання',
    registrationDate: '23.03.2024',
    nextVisit: '27.03.2024',
    nextReminder: '26.03.2024',
  },
  {
    id: '4',
    number: 4,
    name: 'Іван Петрович',
    avatar: '/avatars/patient4.jpg',
    status: 'checkup',
    phoneNumber: '+3804444444',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Запит на інформацію',
    registrationDate: '24.03.2024',
    nextVisit: '28.03.2024',
    nextReminder: '27.03.2024',
  },
  {
    id: '5',
    number: 5,
    name: 'Софія Андріївна',
    avatar: '/avatars/patient5.jpg',
    status: 'partially_treated',
    phoneNumber: '+3805555555',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Обговорення проекту',
    registrationDate: '25.03.2024',
    nextVisit: '29.03.2024',
    nextReminder: '28.03.2024',
  },
  {
    id: '6',
    number: 6,
    name: 'Олег Іванович',
    avatar: '/avatars/patient6.jpg',
    status: 'refused',
    phoneNumber: '+3806666666',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Статус проекту',
    registrationDate: '26.03.2024',
    nextVisit: '30.03.2024',
    nextReminder: '29.03.2024',
  },
  {
    id: '7',
    number: 7,
    name: 'Анна Володимирівна',
    avatar: '/avatars/patient7.jpg',
    status: 'being_treated',
    phoneNumber: '+3807777777',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Планування зустрічі',
    registrationDate: '27.03.2024',
    nextVisit: '31.03.2024',
    nextReminder: '30.03.2024',
  },
  {
    id: '8',
    number: 8,
    name: 'Михайло Олександрович',
    avatar: '/avatars/patient8.jpg',
    status: 'did_not_visit',
    phoneNumber: '+3808888888',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Аналіз даних',
    registrationDate: '28.03.2024',
    nextVisit: '01.04.2024',
    nextReminder: '31.03.2024',
  },
  {
    id: '9',
    number: 9,
    name: 'Тетяна Миколаївна',
    avatar: '/avatars/patient9.jpg',
    status: 'checkup',
    phoneNumber: '+3809999999',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Розробка стратегії',
    registrationDate: '29.03.2024',
    nextVisit: '02.04.2024',
    nextReminder: '01.04.2024',
  },
  {
    id: '10',
    number: 10,
    name: 'Віктор Сергійович',
    avatar: '/avatars/patient10.jpg',
    status: 'partially_treated',
    phoneNumber: '+3801010101',
    executedAmount: '-',
    paid: '-',
    plannedAmount: '-',
    comment: 'Консультація',
    registrationDate: '30.03.2024',
    nextVisit: '03.04.2024',
    nextReminder: '02.04.2024',
  },
]

export const mockPatients = basePatients

export const patientStatuses = {
  did_not_visit: 'Не відвідував клініку',
  had_visit_no_treatment: 'Був візит і не почали лікування',
  being_treated: 'Лікується',
  checkup: 'Профогляд',
  partially_treated: 'Частково проліковано',
  refused: 'Відмова',
} as const

export const patientStatusOptions = [
  { value: 'did_not_visit', label: 'Не відвідував клініку' },
  { value: 'had_visit_no_treatment', label: 'Був візит і не почали лікування' },
  { value: 'being_treated', label: 'Лікується' },
  { value: 'checkup', label: 'Профогляд' },
  { value: 'partially_treated', label: 'Частково проліковано' },
  { value: 'refused', label: 'Відмова' },
] as const

export const sortFieldOptions = [
  { value: 'name', label: "Ім'я" },
  { value: 'status', label: 'Статус' },
  { value: 'phoneNumber', label: 'Телефон' },
  { value: 'email', label: 'Email' },
  { value: 'executedAmount', label: 'Виконана сума' },
  { value: 'paid', label: 'Оплачено' },
  { value: 'plannedAmount', label: 'Запланована сума' },
  { value: 'comment', label: 'Коментар' },
  { value: 'registrationDate', label: 'Дата реєстрації' },
  { value: 'nextVisit', label: 'Наступний візит' },
  { value: 'nextReminder', label: 'Наступне нагадування' },
] as const

export const sortDirectionOptions = [
  { value: 'asc', label: 'За зростанням' },
  { value: 'desc', label: 'За спаданням' },
] as const
